### ISSUE TITLE
Error while exporting service dialogs

### ISSUE THREAD

**Issue by vestival** [rhtconsulting/cfme-rhconsulting-scripts#118]
When we try to export service dialogs it fails with: 

```
# miqexport service_dialogs /tmp/exports/service_dialogs
rake aborted!
NoMethodError: undefined method `dialog_field_responders' for #<DialogFieldDropDownList:0x0000000d8d8a80>
Did you mean?  dialog_group_id
/opt/rh/cfme-gemset/gems/activemodel-5.0.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:160:in `block in export_dialog_fields'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:147:in `export_dialog_fields'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:169:in `block in export_dialog_groups'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:168:in `export_dialog_groups'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:177:in `block in export_dialog_tabs'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:176:in `export_dialog_tabs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:136:in `block in export_dialogs'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:135:in `export_dialogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:9:in `export'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:206:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:service_dialogs:export
(See full trace by running task with --trace)
```

If we try to do the rake, it says the same

```
bin/rake rhconsulting:service_dialogs:export[${BUILDDIR}/service_dialogs]
rake aborted!
NoMethodError: undefined method `dialog_field_responders' for #<DialogFieldDropDownList:0x0000000c09dc18>
Did you mean?  dialog_group_id
/opt/rh/cfme-gemset/gems/activemodel-5.0.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:160:in `block in export_dialog_fields'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:147:in `export_dialog_fields'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:169:in `block in export_dialog_groups'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:168:in `export_dialog_groups'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:177:in `block in export_dialog_tabs'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:176:in `export_dialog_tabs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:136:in `block in export_dialogs'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:135:in `export_dialogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:9:in `export'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:206:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:service_dialogs:export
(See full trace by running task with --trace)
```
With --trace 

```
# bin/rake rhconsulting:service_dialogs:export[${BUILDDIR}/service_dialogs] --trace
** Invoke rhconsulting:service_dialogs:export (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute rhconsulting:service_dialogs:export
rake aborted!
NoMethodError: undefined method `dialog_field_responders' for #<DialogFieldDropDownList:0x0000000d3d9d90>
Did you mean?  dialog_group_id
/opt/rh/cfme-gemset/gems/activemodel-5.0.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:160:in `block in export_dialog_fields'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:147:in `export_dialog_fields'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:169:in `block in export_dialog_groups'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:168:in `export_dialog_groups'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:177:in `block in export_dialog_tabs'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:176:in `export_dialog_tabs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:136:in `block in export_dialogs'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/opt/rh/cfme-gemset/gems/activerecord-5.0.3/lib/active_record/relation/delegation.rb:40:in `map'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:135:in `export_dialogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:9:in `export'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:206:in `block (3 levels) in <top (required)>'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/rh/rh-ruby23/root/usr/share/ruby/monitor.rb:214:in `mon_synchronize'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/rh/cfme-gemset/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
bin/rake:4:in `<main>'
Tasks: TOP => rhconsulting:service_dialogs:expor
```

if I use an older version it works

**Comment by vestival** [comment]
This is the execution with the older version 

```
[root@dsg vmdb]# bin/rake rhconsulting:service_dialogs:export[${BUILDDIR}/service_dialogs]
[root@dsg vmdb]# bin/rake rhconsulting:service_dialogs:export[${BUILDDIR}/service_dialogs] --trace
** Invoke rhconsulting:service_dialogs:export (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute rhconsulting:service_dialogs:export

```

@aelrayess

**Comment by mattparko** [comment]
Ran into the same problem

Older version of rhconsulting_service_dialogs.rake (without updates for dialog_field_responders) works fine.

Currently running cfme-5.7.4.2-1
