### ISSUE TITLE
Import for Service Dialogs and Buttons Broken?

### ISSUE THREAD

**Issue by jeffmcutter** [rhtconsulting/cfme-rhconsulting-scripts#22]
Earlier this week I did this same process successfully, and today I note it is not working as follows:

```
[root@cfme03 miq-VMware-master]# sh -x install.sh 
++ pwd
+ TOPDIR=/tmp/miq-VMware-master
+ DOMAIN=miq-Marketplace
+ '[' -d /tmp/miq-VMware-master/Automate/miq-Marketplace ']'
+ install_cmd
+ echo 'Importing miq-Marketplace from /tmp/miq-VMware-master/Automate/miq-Marketplace'
Importing miq-Marketplace from /tmp/miq-VMware-master/Automate/miq-Marketplace
+ cd /var/www/miq/vmdb
+ echo 'Importing Automate'
Importing Automate
+ bin/rake 'rhconsulting:miq_ae_datastore:import[miq-Marketplace, /tmp/miq-VMware-master/Automate]'
+ echo 'Importing Service Dialogs'
Importing Service Dialogs
+ bin/rake 'rhconsulting:dialogs:import[/tmp/miq-VMware-master/ServiceDialogs]'
Dialog: [VMware - ReconfigVM_HotAddEnabled]
rake aborted!
DialogImportExport::ParsedNonDialogYamlError: DialogImportExport::ParsedNonDialogYamlError
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:43:in `rescue in import_dialogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:32:in `import_dialogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:28:in `import_dialogs_from_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:19:in `block (2 levels) in import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:17:in `foreach'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:17:in `block in import'
/opt/rh/cfme-gemset/bundler/gems/rails-4842a8377644/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/opt/rh/cfme-gemset/bundler/gems/rails-4842a8377644/activerecord/lib/active_record/transactions.rb:208:in `transaction'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:16:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_dialogs.rake:138:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:dialogs:import
(See full trace by running task with --trace)
+ echo 'Importing Buttons'
Importing Buttons
+ bin/rake 'rhconsulting:buttons:import[/tmp/miq-VMware-master/Buttons/buttons.yml]'
Button Group: [VMware Tasks]
rake aborted!
Unable to locate dialog: [VMware - MarkVMAsVirtualMachine]
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:76:in `import_resource_actions'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:128:in `block in import_custom_buttons'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:88:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:88:in `import_custom_buttons'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:146:in `block in import_custom_button_sets'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:135:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:135:in `import_custom_button_sets'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:7:in `block in import'
/opt/rh/cfme-gemset/bundler/gems/rails-4842a8377644/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/opt/rh/cfme-gemset/bundler/gems/rails-4842a8377644/activerecord/lib/active_record/transactions.rb:208:in `transaction'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:6:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:231:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:buttons:import
(See full trace by running task with --trace)
```

I was able to copy over the cfme-rhconsulting-scripts-master from earlier this week and use it successfully after doing a make install from it.

A diff of the working and non-working cfme-rhconsulting-scripts-master directories shows:

```
[root@cfme03 tmp]# diff -rq cfme-rhconsulting-scripts-master*
Files cfme-rhconsulting-scripts-master/rhconsulting_dialogs.rake and cfme-rhconsulting-scripts-master.bad/rhconsulting_dialogs.rake differ
[root@cfme03 tmp]# diff cfme-rhconsulting-scripts-master/rhconsulting_dialogs.rake cfme-rhconsulting-scripts-master.bad/rhconsulting_dialogs.rake
61,63c61,69
<       df = dialog_field['type'].constantize.create(dialog_field.reject { |a| ['resource_action_fqname'].include?(a) })
<       unless dialog_field['resource_action_fqname'].blank?
<         df.resource_action.fqname = dialog_field['resource_action_fqname']
---
>       df = dialog_field['type'].constantize.create(dialog_field.reject { |a| ['resource_action'].include?(a) })
>       unless dialog_field['resource_action'].blank?
>         df.resource_action.action = dialog_field['resource_action']['action']
>         df.resource_action.resource_type = dialog_field['resource_action']['resource_type']
>         df.resource_action.ae_namespace = dialog_field['resource_action']['ae_namespace']
>         df.resource_action.ae_class = dialog_field['resource_action']['ae_class']
>         df.resource_action.ae_instance = dialog_field['resource_action']['ae_instance']
>         df.resource_action.ae_message = dialog_field['resource_action']['ae_message']
>         df.resource_action.ae_attributes = dialog_field['resource_action']['ae_attributes']
86c92,99
<         field_attributes["resource_action_fqname"] = dialog_field.resource_action.fqname
---
>         field_attributes["resource_action"] = {}
>         field_attributes["resource_action"]["action"] = dialog_field.resource_action.action
>         field_attributes["resource_action"]["resource_type"] = dialog_field.resource_action.resource_type
>         field_attributes["resource_action"]["ae_namespace"] = dialog_field.resource_action.ae_namespace
>         field_attributes["resource_action"]["ae_class"] = dialog_field.resource_action.ae_class
>         field_attributes["resource_action"]["ae_instance"] = dialog_field.resource_action.ae_instance
>         field_attributes["resource_action"]["ae_message"] = dialog_field.resource_action.ae_message
>         field_attributes["resource_action"]["ae_attributes"] = dialog_field.resource_action.ae_attributes
```

**Comment by branic** [comment]
What version of CloudForms are you using? The differences are changes that were merged in early this week from me. The change allows the export to be imported using the script or using the GUI. I tested these changes with CF 3.2.

**Comment by jeffmcutter** [comment]
The appliance I was having an issue with is on:
5.4.2.0.20150820153254_83e434d 
The one that worked earlier this week is:
5.4.3.1.20151013111241_1c155a5
I was planning to update the 5.4.2 one, but seems to be issues with subscription stuff today.  I can do that and try again when subscription stuff starts working again.

**Comment by branic** [comment]
Are you trying to import an export that was made with the previous version of the script?

If that is the case I'll need to make a change to handle both the old format and new format of the export.

**Comment by jeffmcutter** [comment]
Well I had just tried to use it with miq-VMware, so I'm guessing that miq-VMware export was still in the old format and it needs to support both?

**Comment by georgegoh** [comment]
Pull request #24 addresses this issue.
